alias: ESPHome BLE Advertise
id: ble_parse_data
mode: queued
trigger:
  - platform: event
    event_type: esphome.on_ble_advertise
action:
  - service: ble_monitor.parse_data
    data:
      packet: "{{ trigger.event.data.packet }}"
      gateway_id: "{{ trigger.event.data.gateway_id if trigger.event.data.gateway_id is defined else 'unknown' }}"