default_config:

homeassistant:
  legacy_templates: false
  name: Home
  latitude: !env_var SECRET_ZONE_HOME_LATITUDE
  longitude: !env_var SECRET_ZONE_HOME_LONGITUDE
  elevation: !env_var SECRET_ZONE_HOME_ELEVATION
  unit_system: metric
  time_zone: America/Santiago
  country: CL

  external_url: !env_var SECRET_EXTERNAL_URL
  internal_url: !env_var SECRET_INTERNAL_URL

  # Load packages
  packages: !include packages/packages.yaml
automation: !include automations.yaml
