# Weather prediction
- platform: yr

# Crypto
- platform: coinmarketcap

- platform: coinmarketcap
  currency: ethereum

# Raspberry Pi System Information
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot

# Google Wifi router
- platform: google_wifi
