- alias: 'Good Morning Routine'
  trigger:
    - platform: time
      at: '06:40:00'

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: light.lifx_set_state
      data:
        entity_id: light.family_room_desk
        power: "on"
        brightness: 100
        color_temp: 333
        transition: 60
    - delay: 00:01:00
    # - service: media_player.volume_set
    #   data:
    #     entity_id: media_player.spotify
    #     volume_level: .2
    # - service: media_player.select_source
    #   data:
    #     entity_id: media_player.spotify
    #     source: Family Room
    # - service: media_player.play_media
    #   data:
    #     entity_id: media_player.spotify
    #     media_content_id: spotify:user:blackjid:playlist:1ny4naJwYYlRQPBqQQI61N
    #     media_content_type: playlist
    # - delay: 00:05:00
    # - service: media_player.volume_set
    #   data:
    #     entity_id: media_player.spotify
    #     volume_level: .4
    - delay: 00:10:00
    - service: switch.turn_on
      data:
        entity_id: switch.hall_light
        
