- alias: 'Good Morning Routine'
  trigger:
    - platform: time
      at: '06:40:00'

  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: light.turn_on
      data:
        entity_id: light.living
        transition: 60
    - delay: 00:01:00
    - service: media_player.volume_set
      data:
        entity_id: media_player.spotify
        volume_level: .2
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: Living
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_id: spotify:user:blackjid:playlist:1ny4naJwYYlRQPBqQQI61N
        media_content_type: playlist
    - delay: 00:05:00
    - service: media_player.volume_set
      data:
        entity_id: media_player.spotify
        volume_level: .4
    - delay: 00:10:00
    - service: switch.turn_on
      data:
        entity_id: switch.dining_room
    - service: switch.turn_on
      data:
        entity_id: light.kids_bedroom
        transition: 30