- alias: Sleeping Baby
  trigger:
    platform: template
    value_template: "{{ is_state('media_player.spotify', 'playing') }}"

  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.media_player.spotify.attributes.media_artist == "Sleep Baby Sleep" }}'
    - condition: template
      value_template: '{{ states.media_player.spotify.attributes.source == "Bedroom" }}'

  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom
        transition: 30
    - service: media_player.volume_set
      data:
        entity_id: media_player.spotify
        volume_level: .5
