automation: !include_dir_list automations
light: !include_dir_list entities/lights
switch: !include_dir_list entities/switches
scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
input_boolean: !include_dir_merge_named entities/input_booleans