light: !include_dir_list entities/lights
sensor: !include_dir_list entities/sensors
switch: !include_dir_list entities/switches
command_line: !include_dir_merge_named command_line
input_boolean: !include_dir_merge_named entities/input_booleans
input_select:  !include_dir_merge_named entities/input_selects
